# Generated by Django 5.1.7 on 2025-05-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scrapeditem_delete_scrapeddata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapeditem',
            old_name='text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='scrapeditem',
            old_name='url',
            new_name='url_base',
        ),
        migrations.RemoveField(
            model_name='scrapeditem',
            name='keyword',
        ),
    ]
