# Generated by Django 5.2.1 on 2025-05-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_rename_text_scrapeditem_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeditem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
