# Generated by Django 5.2.1 on 2025-05-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_scrapeditem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeditem',
            name='organism',
            field=models.CharField(choices=[('BOE', 'BOE'), ('BOCM', 'BOCM'), ('BOPA', 'BOPA'), ('BOPDIBA', 'BOPDIBA'), ('DOGC', 'DOGC'), ('DOGV', 'DOGV')], default='BOE', max_length=50),
        ),
        migrations.AddField(
            model_name='scrapeditem',
            name='region',
            field=models.CharField(choices=[('Nacional', 'Nacional'), ('Madrid', 'Comunidad de Madrid'), ('Asturias', 'Asturias'), ('Cataluña', 'Cataluña'), ('Valencia', 'Comunidad Valenciana')], default='Nacional', max_length=50),
        ),
    ]
