# Generated by Django 5.2.1 on 2025-05-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_scrapeditem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeditem',
            name='title',
            field=models.TextField(max_length=2000),
        ),
    ]
